import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

# Read the CSV file generated by our lor_testing_script.py
df = pd.read_csv(r'lor_vs_time_varying_requests.csv')
df['lor'] = df['lor'].apply(ast.literal_eval)

# Plot the multi-line graph
plt.figure(figsize=(10, 6))
for index, row in df.iterrows():
    time = range(len(row['lor']))
    sns.lineplot(x=time, y=row['lor'], label=f'Total Requests = {row["simulation"] * 10}')

# Label each axis, title the graph, add an informative legend
plt.xlabel('Time')
plt.ylabel('LOR')
plt.title('LOR vs Time where the value of Total Requests varies')
plt.legend()
plt.grid(True)
plt.show()
